version: '3.8'

services:
  producer:
    container_name: producer
    build:
      context: ../producer
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8081:8081"
    environment:
      KAFKA_SERVERS: kafka:9092
      KAFKA_TOPIC: my-topic
      KAFKA_TOPIC_PARTITIONS: 3
      KAFKA_REPLICATION_FACTOR: 1
    networks:
      -  confluent-kafka-practice_kafka-net

  consumer1-1:
    container_name: consumer1-1
    build:
      context: ../consumer
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - producer
    environment:
      KAFKA_SERVERS: kafka:9092
      KAFKA_TOPIC: my-topic
      KAFKA_CONSUMER_GROUP_ID: my-consumer-group-1
      SLEEP_TIME: 0
    networks:
      -  confluent-kafka-practice_kafka-net

  consumer1-2:
    container_name: consumer1-2
    build:
      context: ../consumer
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - producer
    environment:
      KAFKA_SERVERS: kafka:9092
      KAFKA_TOPIC: my-topic
      KAFKA_CONSUMER_GROUP_ID: my-consumer-group-1
      SLEEP_TIME: 0
    networks:
      -  confluent-kafka-practice_kafka-net
  
  consumer2-1:
    container_name: consumer2-1
    build:
      context: ../consumer
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - producer
    environment:
      KAFKA_SERVERS: kafka:9092
      KAFKA_TOPIC: my-topic
      KAFKA_CONSUMER_GROUP_ID: my-consumer-group-2
      SLEEP_TIME: 0
    networks:
      -  confluent-kafka-practice_kafka-net

  consumer2-2:
    container_name: consumer2-2
    build:
      context: ../consumer
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - producer
    environment:
      KAFKA_SERVERS: kafka:9092
      KAFKA_TOPIC: my-topic
      KAFKA_CONSUMER_GROUP_ID: my-consumer-group-2
      SLEEP_TIME: 5
    networks:
      -  confluent-kafka-practice_kafka-net

  consumer3-1:
    container_name: consumer3-1
    build:
      context: ../consumer
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - producer
    environment:
      KAFKA_SERVERS: kafka:9092
      KAFKA_TOPIC: my-topic
      KAFKA_CONSUMER_GROUP_ID: my-consumer-group-3
      SLEEP_TIME: 2
    networks:
      -  confluent-kafka-practice_kafka-net

networks:
  confluent-kafka-practice_kafka-net:
    external: true
